apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-website
  template:
    metadata:
      labels:
        app: devops-website
    spec:
      containers:
      - name: devops-website
        image: westbrom1968/devops-website:latest
        ports:
        - containerPort: 80
