name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Validate HTML
      - name: Validate HTML
        run: |
          echo "Checking HTML..."
          sudo apt-get update && sudo apt-get install -y tidy
          for file in $(find . -name "*.html"); do
            tidy -qe "$file"
          done

      # Step 3: Validate CSS
      - name: Validate CSS
        run: |
          echo "Checking CSS..."
          for file in $(find . -name "*.css"); do
            curl -s -F "file=@$file" https://jigsaw.w3.org/css-validator/validator \
              | grep -i "error" || echo "No CSS errors in $file"
          done
      
      # Step 4: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-website:latest .

      # Step 6: Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-website:latest
